### PR TITLE
Message properties

### PR DESCRIPTION
**Pull request by useless-stuff**
I'm completely far away to be a Ruby developer I never wrote something serious with this language. 

You should be seriously scared about this code :)

Anyway I've tried to pass some message options for trigger a task in Celery and it wasn't possible, I've played a bit with the code and now it works.

Probably it's the worst way to do that but as I've said I'm not a Ruby developer, forgive me :)

### CODE REVIEW

**Comment by useless-stuff** [comment]
I've signed the CLA :)

**Comment by useless-stuff** [comment]
This is an example of my output config


       ```
rabbitmq
            {
                key             => "celery"
                exchange        => "celery"
                exchange_type   => "direct"
                user            => "${RABBITMQ_USER}"
                password        => "${RABBITMQ_PASSWORD}"
                host            => "${RABBITMQ_HOST}"
                port            => "${RABBITMQ_PORT}"
                durable         => true
                persistent      => true
                properties      => {
                    content_type     => "application/json"
                    content_encoding => "UTF-8"
                }
                codec           => json
            }
```

**Comment by useless-stuff** [comment]
Ehi guys, there is any chance that these changes will be considered? 
I'd like to understand if I need to build a custom plugin :)
Thank you so much!

**Comment by robbavey** [comment]
@useless-stuff Thank you for your contribution! We've included functionality along these lines in the latest version of this plugin - upgrade to v4.0.9 of the logstash-output-rabbitmq plugin. It uses message_properties as the key, rather than properties, but otherwise works the same as per your proposal. 

Thanks again!

**Comment by useless-stuff** [comment]
Thank you too!!
You have saved me from writing a custom plugin that actually, I don't have any idea how can I do that :)

**Comment by robbavey** [comment]
Glad to help @useless-stuff - feel free to close this pull request, and try out the latest version of the plugin. If you have any problems or queries about the implementation, you can open up an issue.

Thanks again!

**Pull request closed without merging**
