### PR TITLE
Fix for #9, #10

### PR DESCRIPTION
**Pull request by ssc-**
Whenever a reconnect happened, a new connection was opened and the new rabbitmq channel was set up without being assigned to the class member @x. Every time the old (broken) channel was accessed, a new reconnect was triggered.

### CODE REVIEW

**Comment by dforste** [comment]
What would it take to get this feature merged?
Logstash keeps filling up the disk/logs with errors.

**Comment by BDeus** [comment]
same here, it is possible to pull this request?

**Comment by leneurone** [comment]
And same here ! Could this request be merged please ?

**Comment by andrewvc** [comment]
@leneurone @ssc- I'll work on getting this merged ASAP. This module is lacking tests, would you be able to add a spec for this bugfix to the existing tests?

**Comment by ssc-** [comment]
@andrewvc Thanks for merging. I'm quite new to ruby, but I'll try to add a spec. Is there a simpler way to test this bug, than to mock at least parts of march_hare?

**Comment by andrewvc** [comment]
@ssc- don't worry about the specs, I'm actually writing them right now. Thanks so much for tracking down this bug and submitting a PR

**Pull request merged**
